services:
  - type: web
    name: myapp-web
    env: ruby
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec puma -C config/puma.rb
    domains:
      - yourdomain.com # Substitua pelo seu nome de domínio
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: myapp-redis
          type: pserv
          property: hostport
      - key: RAILS_MASTER_KEY
        sync: false

  - type: worker
    name: myapp-sidekiq
    env: ruby
    plan: starter
    buildCommand: bundle install
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec sidekiq -e production
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: myapp-redis
          type: pserv
          property: hostport
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: portifolio
    databaseName: portifolio
    user: palermoc
    plan: free

 - type: pserv
    name: myapp-redis
    env: docker
    repo: https://github.com/render-examples/redis.git
    numInstances: 1
    disk:
      name: myapp-redis-data
      mountPath: /var/lib/redis
      sizeGB: 1
